# Generated by Django 4.1.7 on 2023-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='IsActive'),
        ),
    ]
