# Generated by Django 4.1.7 on 2023-09-03 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='measurement_range',
            field=models.IntegerField(blank=True, default=15, validators=[django.core.validators.StepValueValidator(15, 'O número informado não é valido.')], verbose_name='Intervalo de medicão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0.')], verbose_name='Capacidade do aparelho (L)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descrição do aparelho'),
        ),
        migrations.AlterField(
            model_name='device',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Localização do aparelho'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome do Proprietário'),
        ),
    ]
