# Generated by Django 4.1.7 on 2023-09-12 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_measurement_range_alter_device_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0.')], verbose_name='Capacidade do reservatório (L)'),
        ),
    ]
