# Generated by Django 4.1.7 on 2023-10-24 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da medição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='capacity',
            field=models.FloatField(blank=True, verbose_name='Capacidade do reservatório (L)'),
        ),
    ]
