# Generated by Django 4.1.7 on 2023-10-31 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_measure_created_date_alter_measure_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="latitude",
            field=models.FloatField(
                blank=True, default=-22.996618, verbose_name="Latitude"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="longitude",
            field=models.FloatField(
                blank=True, default=-22.996618, verbose_name="Longitude"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="device",
            name="measurement_range",
            field=models.IntegerField(
                blank=True,
                validators=[
                    django.core.validators.StepValueValidator(
                        1, "O número informado não é valido."
                    ),
                    django.core.validators.MinValueValidator(
                        1, "A quantidade mínima para medição diária é 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "A quantidade máxima para medição diária é de 5."
                    ),
                ],
                verbose_name="Intervalo de medicão",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="place",
            field=models.CharField(
                max_length=100, verbose_name="Descrição da localização"
            ),
        ),
    ]
